name: hortinha
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_icons: ^0.1.3
  flutter_sticky_header: ^0.3.4



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#  assets:
#  - assets/fundo.jpg
#  - assets/logoSicredi.png
